[package]
name = "advent-of-code"
version = "5.0.0"
edition = "2024"

[dependencies]
temp-env = { version = "0.3.*" }
indicatif = { version = "0.17.*" }

[[bin]]
name = "TEMPLATE_PACKAGE_NAME"
path = "templates/day_xx/src/main.rs"